---
- hosts: client
  tasks:
    - name: Update and upgrade
      become: true
      apt: 
        upgrade: dist
        update_cache: yes
        cache_valid_time: 36000	#10 hours
        
    - name: install tasksel
      apt: name=tasksel state=present 
        
    - name: Install gnome
      shell: tasksel install gnome-dekstop --new-install
        
    - name: Changing directory to access sources list
      shell: 
        cd ..
        cd etc/apt
        echo -e "deb http://packages.linuxmint.com debian import\n" >> sources.list
   
    - name: Update system
      become: true
      apt:
        upgrade: dist      
        update_cache: yes
        cache_valid_time: 36000	#10 hours
    
    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
        - firefox-mozilla-build
